# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# MySQL
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: <%= ENV.fetch("MYSQL_USER") { "" } %>
#   password: <%= ENV.fetch("MYSQL_PASSWORD")  { "" } %>
#   host: <%= ENV.fetch("MYSQL_HOST") { "" }  %>
#   database: <%= ENV.fetch("MYSQL_DBNAME") { "" }  %>
#   socket: /var/run/mysqld/mysqld.sock

# PostgreSQL
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD")  { "" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "" }  %>
  database: <%= ENV.fetch("POSTGRES_DBNAME") { "" }  %>

development:
  <<: *default
  # database: storage/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  # database: storage/test.sqlite3

# production:
#   <<: *default
#   database: storage/production.sqlite3

# MySQL
# production:
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: <%= ENV.fetch("MYSQL_USER") { "" } %>
#   password: <%= ENV.fetch("MYSQL_PASSWORD")  { "" } %>
#   host: <%= ENV.fetch("MYSQL_HOST") { "" }  %>
#   database: <%= ENV.fetch("MYSQL_DBNAME") { "" }  %>

# PostgreSQL
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD")  { "" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "" }  %>
  database: <%= ENV.fetch("POSTGRES_DBNAME") { "" }  %>